USE bestiu_rentals;

INSERT INTO listings (
  id,
  title,
  area_key,
  area,
  district,
  state,
  rent_inr,
  distance_to_campus_km,
  type,
  suitable_for_json,
  amenities_json,
  contact
) VALUES
(
  'LST-001',
  'Student-friendly shared room',
  'gorantla',
  'Gorantla',
  'Sri Sathya Sai',
  'Andhra Pradesh',
  3200,
  1.40,
  'Shared Room',
  JSON_ARRAY('Students'),
  JSON_ARRAY('Wi-Fi', 'Study Table', 'Water'),
  '+91-90000-10001'
),
(
  'LST-002',
  'Family apartment near market',
  'gorantla',
  'Gorantla',
  'Sri Sathya Sai',
  'Andhra Pradesh',
  8500,
  2.80,
  '1BHK',
  JSON_ARRAY('University Staff', 'Families'),
  JSON_ARRAY('Parking', 'Power Backup', 'Water'),
  '+91-90000-10002'
),
(
  'LST-003',
  'Boys hostel beds',
  'gownivaripalli',
  'Gownivaripalli',
  'Sri Sathya Sai',
  'Andhra Pradesh',
  4200,
  0.70,
  'Hostel',
  JSON_ARRAY('Students'),
  JSON_ARRAY('Food', 'Wi-Fi', 'Security'),
  '+91-90000-10003'
),
(
  'LST-004',
  'Private room on Bagepalli road',
  'bagepalli',
  'Bagepalli',
  'Chikkaballapur',
  'Karnataka',
  5000,
  21.00,
  'Private Room',
  JSON_ARRAY('Students', 'University Staff'),
  JSON_ARRAY('Wi-Fi', 'Attached Bath'),
  '+91-90000-10004'
),
(
  'LST-005',
  'Budget independent room',
  'bagepalli',
  'Bagepalli',
  'Chikkaballapur',
  'Karnataka',
  3600,
  18.20,
  'Single Room',
  JSON_ARRAY('Students'),
  JSON_ARRAY('Water', 'Wardrobe'),
  '+91-90000-10005'
),
(
  'LST-006',
  'Staff quarter style 2BHK',
  'gorantla',
  'Gorantla',
  'Sri Sathya Sai',
  'Andhra Pradesh',
  12000,
  3.50,
  '2BHK',
  JSON_ARRAY('University Staff', 'Families'),
  JSON_ARRAY('Parking', 'Power Backup', 'Gated'),
  '+91-90000-10006'
)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  area_key = VALUES(area_key),
  area = VALUES(area),
  district = VALUES(district),
  state = VALUES(state),
  rent_inr = VALUES(rent_inr),
  distance_to_campus_km = VALUES(distance_to_campus_km),
  type = VALUES(type),
  suitable_for_json = VALUES(suitable_for_json),
  amenities_json = VALUES(amenities_json),
  contact = VALUES(contact);
